# Generated by Django 2.0.4 on 2018-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousurl',
            name='hash_text',
            field=models.TextField(default='xZxzcasd', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userurl',
            name='hash_text',
            field=models.TextField(default='adasdaqw', max_length=8),
            preserve_default=False,
        ),
    ]
