# Generated by Django 2.0.4 on 2018-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0003_userphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='no_of_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
