# Generated by Django 2.0.4 on 2018-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0004_userurl_no_of_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='page_desc',
            field=models.TextField(default='no title', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userurl',
            name='page_title',
            field=models.TextField(default='no desc', max_length=10000),
            preserve_default=False,
        ),
    ]
