# Generated by Django 2.0.4 on 2018-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0005_auto_20180507_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='page_desc',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='page_title',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
