# Generated by Django 2.0.4 on 2018-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0008_auto_20180507_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='page_icon_url',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
