# Generated by Django 2.0.4 on 2018-05-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0010_userurlstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userurlstatistics',
            options={'verbose_name': 'User URL Statistics', 'verbose_name_plural': 'User URL Statistics'},
        ),
    ]
