# Generated by Django 2.0.4 on 2018-05-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0011_auto_20180520_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userurlstatistics',
            old_name='user_url',
            new_name='url',
        ),
    ]
