# Generated by Django 2.0.4 on 2018-07-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0011_auto_20180523_0940'),
        ('shortify', '0012_auto_20180520_0650'),
    ]

    operations = [
    ]
