# Generated by Django 2.0.4 on 2018-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0013_merge_20180714_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurlstatistics',
            name='date_clicked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
