# Generated by Django 2.0.4 on 2018-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0013_userphonenumber_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/img_avatar2.png', upload_to='pictures/'),
        ),
    ]
